### PR TITLE
Early task describe-partialy work

### PR DESCRIPTION
**Pull request by Degoot-AM**
This PR is intended to include some changes before moving to new layout of the platform.

### CODE REVIEW

**Comment by avallecam** [comment]
Hi @Degoot-AM thank you for contribution and for requesting this review to me and @Karim-Mane . If there is any specific feedback you prefer to prioritize, let me know!

One thing to solve, could you resolve the conflicts of this branch with respect to `main`? Just in case, I summarised some steps on how to use `git rebase` to solve these conflicts locally in the [contributing guides](https://github.com/epiverse-trace/tutorials/blob/main/CONTRIBUTING.md#rebase)

**Comment by Degoot-AM** [comment]
The conflicts with main branch now has been resolved. However, I could not run the benchwork suit locally. Below is the error: 
```
sandpaper::build_lesson()
Error in `purrr::map()`:
ℹ In index: 1.
ℹ With name: describe-cases.Rmd.
Caused by error:
! argument "..2" is missing, with no default
Run `rlang::last_trace()` to see where the error occurred.
```

**Comment by Degoot-AM** [comment]
https://github.com/epiverse-trace/tutorials-early/pull/10#issuecomment-2014910372. Thanks to @Bisaloo Regular updates of {pegboard} solve this building issue.

**Review by Karim-Mane — APPROVED** [review]

**Comment by avallecam** [comment]
Hi @Degoot-AM , is preferable to let all checks pass before the merging. This helps to catch any error with anticipation before getting them on the website. 

Is it ok if I temporarily block the added episodes and then open a new PR to solve these issues there?

**Comment by avallecam** [comment]
> Is it ok if I temporarily block the added episodes and then open a new PR to solve these issues there?

Needed to go ahead to clean `main` and merge PR #17 

Done in:
- https://github.com/epiverse-trace/tutorials-early/commit/9855fca3d40cb0bb9da4a72d6f5429ab68b95d6c
- https://github.com/epiverse-trace/tutorials-early/commit/73133d883bb92cd1a193785716f00eba060d96c6
- https://github.com/epiverse-trace/tutorials-early/commit/0f76b1a8c2314ba5f976838b1eca34845d3e113d

Created branch: https://github.com/epiverse-trace/tutorials-early/tree/fix-read-describe-cases

**Pull request merged**
